---
- name: Check HAProxy
  stat: path=/etc/haproxy
  register: haproxy_dir
  tags:
   - haproxy

- name: Setup HAProxy script
  copy: src=haproxy_dns_cfg dest="{{ haproxy_script_location }}/haproxy_dns_cfg" mode=755
  when: haproxy_dir.stat.exists
  tags:
   - haproxy

- name: Create HAProxy reload script
  template: src=haproxy_reload.j2 dest={{ haproxy_script_location }}/haproxy_reload
    owner="root" group="root" mode=0744
  when: haproxy_dir.stat.exists
  tags:
   - haproxy

- name: Setup cron job for HAProxy
  cron: name="reload marathon haproxy" minute="*/1" job="{{ haproxy_script_location }}/haproxy_reload"
  when: haproxy_dir.stat.exists
  tags:
   - haproxy

- name: Setup haproxy reload webhook
  copy: src=marathon-haproxy-webhook dest="{{ haproxy_script_location }}/marathon-haproxy-webhook" mode=755
  when: haproxy_dir.stat.exists
  tags:
   - haproxy

- name: Install haproxy reload webhook dependencies 1
  apt: package=python-pip state=installed
  
- name: Install haproxy reload webhook dependencies 2
  shell: "pip install flask"

- name: Copy initd file
  copy: src=marathon-haproxy-webhook.initd dest=/etc/init.d/marathon-haproxy-webhook mode=755

- name: Enable and start marathon-haproxy-webhook
  service: name=marathon-haproxy-webhook state=started enabled=yes
