#!/usr/bin/env python

import flask
import os

app = flask.Flask('marathon-haproxy-webhook', static_url_path='')

@app.route('/marathon-haproxy-webhook', methods=['POST'])
def index():
    json = flask.request.get_json(force=True)
    if json['eventType'] == 'status_update_event' and json['taskStatus'] in ['TASK_RUNNING', 'TASK_FAILED', 'TASK_KILLED', 'TASK_LOST']:
        reloadHaproxy()
    return 'Success'

def reloadHaproxy():
    print('Reloading haproxy')
    os.system('/usr/local/bin/haproxy_reload')


app.debug=False
app.run(port=8083, host='0.0.0.0')